### ISSUE TITLE
Wrong interpretation of transparency on OUTLINE

### ISSUE THREAD

**Issue by aperi2007** [faunalia/rt_mapserver_exporter#10]
I notice the plugin use a deprecate comand (OPACITY) in the outline section.

It is using a deprecated solution with the OPACITY instead of the 4th parameter in hexadecimal.

Infact the standard solution for a 50% transparency on the outline should be set like this:
COLOR "#RRGGBBTT"
where TT = FF (in hexadecimal) mean NO TRANSPARENCY and TT=00 (in hexadecimal) mean FULL TRANSPARENCY

Actually the plugin is using the opacity:

COLOR RR GG BB (where RR GG and BB are in decimal )
OPACITY TT (where TT is transparency in decimal).

I will try to resolve this in my locally version of plugin (I'm using a heavy customized fork of rt_mapserver_.exporter).
If the solution will be quite standard I will produce a pull for this version.

**Comment by luipir** [comment]
are you sure? TT would be at the beginning of # string.

btw... thank you to share and test modification. waiting for it.

**Comment by aperi2007** [comment]
Yes , I'm sure.

The transparent in mapserver is at the end of string.

**Comment by aperi2007** [comment]
I close this ticket and re-open another to explain better
