### ISSUE TITLE
Will this project be continued someday?

### ISSUE THREAD

**Issue by umbe1987** [faunalia/rt_mapserver_exporter#18]
I really love the idea: exporting QGIS projects directly in Mapserver Mapfiles that can be used in WebGIS application such as OpenLayers.
I would love to use such a feature.
Big question: any chance this project gonna live again?
Is the problem more related to maintain it as a QGIS plugin as QGIS versions go on (especially now that version 3 is using Qt5), or does it lie in the difficult to mantain the main functionality (i.e. MapfileExporter.py script)?

**Comment by pcav** [comment]
This approach proved very heavy to maintain, especially when considering the semantic richness of QGIS styling when compared to Mapserver. We therefore discontinued development in favour of direct usage of QGIS-server.
You are welcome to resume development of the plugin if you think is the best choice for you.
