### ISSUE TITLE
rt_mapserver_export

### ISSUE THREAD

**Issue by fpkcimino** [faunalia/rt_mapserver_exporter#2]
DOESN'T WORK. on windows 8?
error: No module named mapscript

Errore durante l'esecuzione di codice Python:

Traceback (most recent call last):
  File "C:\Users\francesco/.qgis2/python/plugins\rt_mapserver_exporter\plugin.py", line 65, in run
    from .mapfileexportdlg import MapfileExportDlg
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 453, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\francesco/.qgis2/python/plugins\rt_mapserver_exporter\mapfileexportdlg.py", line 30, in 
    import mapscript
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 453, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named mapscript

Versione Python:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]

Versione di QGIS:
2.0.1-Dufour Dufour, d94c044

**Comment by luipir** [comment]
as said by the log message: ImportError: No module named mapscript
install mapscript modules... did you installed using OSGeo4W? run again OSGeo4W and look for packages with name mapscript, you'll find mapscript and python-mapscript (the others are nos used  by this plugin)

really I didn't test on W8, but it should work

**Comment by luipir** [comment]
please verify if it works and if yes, please close this issue

**Comment by fpkcimino** [comment]
just did it and it works!
As you said i missed something in osgeo installation.
Thanks a lot!
